const express = require("express")
const route = express.Router()
const ctl = require("../Controller/ctl")
const passport = require("../middleware/passport")
const uploads = require("../middleware/multer")

route.get("/", ctl.login)
route.get("/dashboard", passport.Auth, ctl.dashboard)
route.get("/Form", passport.Auth, ctl.Form)
route.get("/table", passport.Auth, ctl.table)
route.post("/addData", passport.Auth, uploads, ctl.addData)
route.get("/delete", passport.Auth, ctl.deleteadmin)
route.get("/edit", passport.Auth, ctl.editadmin)
route.post("/UpdateData", passport.Auth, ctl.updateAdmin)
route.post("/login", passport.authenticate("local", { failureRedirect: "/" }), ctl.auth)
route.get("/logout", ctl.logout)
route.get("/profile", passport.Auth, ctl.profile)
route.get("/changepass",passport.Auth,ctl.changepass)
route.post("/changepassword",passport.Auth,ctl.updatepassword)

module.exports = route